version: '2'
services:
  odoo14:
    image: shabanash/cargomate_odoo
    user: root
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=34.93.62.198
      - USER=postgres
      - PASSWORD=qO4L7y0f1qMm674K
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
