version: '2'
services:
  odoo14:
    image: shabanash/cargomate_odoo
    user: root
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=10.55.0.3
      - USER=odoo
      - PASSWORD=CargoMate@123
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
